Section "OutputClass"
    Identifier "zx"
    MatchDriver "zx"
    Driver "zx"
EndSection

Section "Device"
    Identifier "VideoCard1"
    Driver "zx"
    VendorName "ZhaoXin Graphics, Inc."
EndSection
